### ISSUE TITLE
Add an option for headless installation

### ISSUE THREAD

**Issue by edorgeville** [node-red/raspbian-deb-package#6]
Hi,
I'm currently working on a setup with about 80+ Rpi3 that will be setup using Ansible.
The install script (https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered) asks for confirmation, which blocks the install as no keyboard input is possible.
Adding a `-y` option for the script would be a solution for people like me trying to automate their installation. 

I'd do a PR but I don't have much bash skills so I'm not exactly sure how to do it. 
Let me know if I can help in any other way 😉 

Thanks !

**Comment by dceejay** [comment]
or just create you own version of the script and remove that line ?
and the bit at the end where it goes and tries to update the script.

**Comment by dceejay** [comment]
Testing with

    echo Y | update-nodejs-and-nodered 

seems to work well. Is that sufficient ?

**Comment by edorgeville** [comment]
Totally is ! I will test it soon with Ansible and let your know. In the meantime, I'm closing this issue. Thanks !

**Comment by edorgeville** [comment]
Update on this, I ended up using Ansible to manage deploys, here is the node-red installation part : 
```yaml
    - name: Update node-red
      tags: setup
      become: true
      when: update_nodered
      block:
        - apt:
            name: "{{ item }}"
            state: absent
          with_items:
            - nodejs
            - nodejs-legacy
            - npm
        - file:
            state: absent
            path: '/usr/local/bin/npm'
        - file:
            state: absent
            path: '/etc/apt/sources.d/nodesource.list'
        - apt: 
            autoremove: yes
        - script: scripts/setup_nodejs_8.x.sh # https://deb.nodesource.com/setup_8.x
        - apt:
            name: nodejs
            state: present
        - npm:
            name: node-red
            state: present
            global: yes
            version: '0.18.3'
```
Not really using the script anymore 😜

**Comment by dceejay** [comment]
Nice !  (though we are on release 0.18.5 now ;-)
i don't know enough about Ansible to know if this is a sufficient script to both install from scratch and / or upgrade an existing installation. If so - is there a place where this could be shared ?

**Comment by edorgeville** [comment]
I've tested this script against multiple installs, but added some conditions to skip the whole block if the version matches the target. For that I use the following tasks:
```yaml
- name: Is nodered installed?
      tags: setup
      stat:
        path: /usr/bin/node-red
      register: nodered_install
    - name: Default nodered facts
      tags: setup
      set_fact:
        nodered_version_major: 0
        nodered_version_minor: 0
        nodered_version_patch: 0
    - name: Get nodered version
      tags: setup
      when: nodered_install.stat.exists
      command: "node-red --help"
      register: nodered_help
      changed_when: False
    - name: Save node-red version to facts
      tags: setup
      when: nodered_install.stat.exists
      set_fact:
        nodered_version_major: '{{ nodered_help.stdout_lines[0].replace("Node-RED v", "").split(".")[0] }}'
        nodered_version_minor: '{{ nodered_help.stdout_lines[0].replace("Node-RED v", "").split(".")[1] }}'
        nodered_version_patch: '{{ nodered_help.stdout_lines[0].replace("Node-RED v", "").split(".")[2] }}'
    - name: Should we update node-red ?
      tags: setup
      set_fact:
        update_nodered: "{{ nodered_version_minor|int < 18}}"
```
(not really future proof but this was for a short term setup)


I'm still learning Ansible, but from what I've read this task list could be adapted into an [Ansible role](http://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html).  
After that, the role could be shared on [Ansible Galaxy](https://galaxy.ansible.com/). Feel free to look into it, I don't think I'll have time in the near future 😅
